# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     # 克隆代码
    - name: Checkout
      uses: actions/checkout@v4

    # 设置Node环境
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: npm

    # 安装依赖
    - name: Install dependencies
      run: npm install

    # 编译
    - name: Build
      run: npm run build
