# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     # 克隆代码
    - name: Checkout
      uses: actions/checkout@v4

    # 设置Node环境
    - uses: pnpm/setup@v1
      with:
        version: 11.2.2
        runtime: node@24
        cache: true

    # 安装依赖
    - name: Install dependencies
      run: pnpm i

    # 编译
    - name: Build
      run: |
        pnpm build
        tar -czf arkrog-frontend-${{ github.ref_name }}.tgz -C build/client .
      
    # 上传产物
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: arkrog-frontend-${{ github.ref_name }}.tgz

    # 部署
    - name: Deploy
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: arkrog-frontend-${{ github.ref_name }}.tgz
        target: "/root/workspace/arkrog"
